import xml.sax.saxutils as saxutils
from typing import Dict, Any, List

class KMLExporter:
    """Generates standard OGC KML 2.2 files for Google Earth visualization."""

    @classmethod
    def export_flood_kml(cls, simulation_result: Dict[str, Any], scenario: Dict[str, Any]) -> str:
        """Constructs KML XML with styles, dam placemark, and multi-timestep flood extents."""
        sc_name = saxutils.escape(str(scenario.get("name", "Flood Simulation")))
        dam = scenario.get("dam", {})
        dam_name = saxutils.escape(str(dam.get("name", "Dam Structure")))
        river = saxutils.escape(str(dam.get("river", "River")))
        dam_lat = dam.get("lat", 30.3778)
        dam_lng = dam.get("lng", 78.4806)

        time_steps = simulation_result.get("timeSteps", [])
        last_step = time_steps[-1] if time_steps else None
        
        # Build polygon placemarks
        polygons_kml = []
        if last_step:
            coords = last_step.get("floodExtentGeoJSON", {}).get("geometry", {}).get("coordinates", [[]])[0]
            coord_str = " ".join([f"{c[0]},{c[1]},0" for c in coords if len(c) >= 2])
            area = last_step.get("inundationArea", simulation_result.get("inundationArea", 235))
            depth = last_step.get("maxDepth", simulation_result.get("maxDepth", 8.4))

            polygons_kml.append(f"""
    <Placemark>
      <name>Peak Inundation Extent (T+ {last_step.get('time', 6)}h)</name>
      <description><![CDATA[
        <b>Inundation Area:</b> {area} km²<br/>
        <b>Max Depth:</b> {depth} m<br/>
        <b>Arrival Time:</b> {simulation_result.get('arrivalTime', 3.4)} hrs<br/>
        <b>Authority:</b> National Dam Safety Authority
      ]]></description>
      <styleUrl>#floodPolyStyle</styleUrl>
      <Polygon>
        <tessellate>1</tessellate>
        <outerBoundaryIs>
          <LinearRing>
            <coordinates>{coord_str}</coordinates>
          </LinearRing>
        </outerBoundaryIs>
      </Polygon>
    </Placemark>""")

        kml_content = f"""<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
  <Document>
    <name>SETRA – {sc_name}</name>
    <description>Simulated 2D Hydrodynamic Flood Extent for {dam_name} ({river}). Generated by SETRA Platform.</description>
    <Style id="damPlacemark">
      <IconStyle>
        <scale>1.3</scale>
        <Icon>
          <href>http://maps.google.com/mapfiles/kml/shapes/placemark_circle.png</href>
        </Icon>
      </IconStyle>
      <LabelStyle><scale>0.9</scale></LabelStyle>
    </Style>
    <Style id="floodPolyStyle">
      <LineStyle>
        <color>ff1677ff</color>
        <width>2.5</width>
      </LineStyle>
      <PolyStyle>
        <color>7fd9c420</color>
        <fill>1</fill>
        <outline>1</outline>
      </PolyStyle>
    </Style>
    <Placemark>
      <name>{dam_name}</name>
      <description><![CDATA[
        <b>Structure:</b> {dam_name}<br/>
        <b>River:</b> {river}<br/>
        <b>Height:</b> {dam.get('height', 'N/A')} m<br/>
        <b>Reservoir Level:</b> {scenario.get('reservoirLevel', 'N/A')} m MSL
      ]]></description>
      <styleUrl>#damPlacemark</styleUrl>
      <Point>
        <coordinates>{dam_lng},{dam_lat},0</coordinates>
      </Point>
    </Placemark>
    {''.join(polygons_kml)}
  </Document>
</kml>"""
        return kml_content
